sudo: required

services:
  - docker

before_install:
  - docker build -t couchdb:1.6.1 1.6.1
  - docker build -t couchdb:1.6.1-couchperuser 1.6.1-couchperuser

script:
  - docker run -d -p 5984:5984 couchdb:1.6.1 && sleep 5 && curl http://localhost:5984
  - docker run -d -p 5985:5984 couchdb:1.6.1-couchperuser && sleep 5 && curl http://localhost:5985
